import os


srcs = [
	"src/memory.cpp",
]

includes = [".", "..", "include"]

cxx = ""
compmode = ""
platform = ""
sanitize = ""
compile_commands = "y"
cflags = "-std=c++20 -Wall -Wextra -Wpedantic"
ldflags = ""

def input_stuff():
	global cxx, compmode, platform, sanitize, compile_commands, cflags, ldflags

	print("libtrippin auto configurator 3000++")
	cxx = input("* compiler [g++, clang++]: ")
	compmode = input("* compile mode [debug/release]: ")
	assert compmode == "debug" or compmode == "release"
	platform = input("* platform [windows/linux]: ")
	assert platform == "windows" or platform == "linux"
	sanitize = input("* [optional] use a sanitizer: ")
	compile_commands = input("* [optional] generate compile_commands.json for clangd? [Y/n]: ")
	if compile_commands == "":
		compile_commands = "y"
	assert compile_commands == "y" or compile_commands == "n"

	if cxx == "g++" and platform == "windows":
		cxx = "x86_64-w64-mingw32-g++"

	for include in includes:
		cflags += f" -I{include}"

	if platform == "windows":
		ldflags = "-lstdc++ -static"
	else:
		ldflags = "-lm"

	if compmode == "debug":
		cflags += " -O0 -g -DDEBUG -D_DEBUG"
	else:
		cflags += " -O3 -g -fno-omit-frame-pointer"

	if sanitize != "":
		cflags += f" -fsanitize={sanitize}"
		ldflags += f" -fsanitize={sanitize}"

def gen_build_file():
	global cxx, compmode, platform, sanitize, compile_commands, cflags, ldflags

	with open("build.ninja", "w") as f:
		f.write(
f"""# Autogenerated by configure.py. You probably shouldn't edit this.
cxx = {cxx}
cflags = {cflags}
ldflags = {ldflags}
ar = ar
arflags = rcs

rule compile
  command = $cxx $cflags -c $in -o $out
  description = Compiling $in

rule link
  command = $cxx $in $ldflags -o $out
  description = Linking $out

rule archive
  command = $ar $arflags $out $in
  description = Archiving $out
"""
		)

		# build crap
		for src in srcs:
			f.write(f"build {src.replace(".cpp", ".o")}: compile {src}\n")

		# im archiving it
		f.write("\nbuild libtrippin.a: archive ")
		for src in srcs:
			f.write(f"{src.replace(".cpp", ".o")} ")

		f.write("\ndefault libtrippin.a\n")

if __name__ == "__main__":
	input_stuff()
	gen_build_file()
	if compile_commands == "y":
		assert os.system("ninja -t compdb > compile_commands.json") == 0
	print("ok")
