#!/bin/lua
local test_srcs = {
	"examples/test_all.cpp",
}
local srcs = {
	"trippin/common.cpp",
	"trippin/error.cpp",
	"trippin/iofs.cpp",
	"trippin/log.cpp",
	"trippin/math.cpp",
	"trippin/memory.cpp",
	"trippin/string.cpp",
	"trippin/util.cpp",
}

local includes = {".", ".."}

io.write("libtrippin auto configurator 3000++\n")

io.write("- compiler, e.g. clang++ > ")
local cxx = io.read("*l")

io.write("- compile mode [debug/release] > ")
local compmode = io.read("*l")
assert(compmode == "debug" or compmode == "release")

io.write("- target platform [windows/linux] > ")
local platform = io.read("*l")
assert(platform == "linux" or platform == "windows")

io.write("- use a sanitizer? maps directly to a -fsanitize flag. you can usually ignore this. > ")
local sanitize = io.read("*l")

io.write("- generate compile_commands.json for clangd? [Y/n] > ")
local compile_commands = io.read("*l")
if compile_commands == "" then compile_commands = "y" end
assert(compile_commands == "y" or compile_commands == "n")

io.write("generating...\n")

if cxx == "g++" and platform == "windows" then
	cxx = "x86_64-w64-mingw32-g++"
end

local cflags = "-std=c++20 -Wall -Wextra -Wpedantic "

for _, include in ipairs(includes) do
	cflags = cflags .. " -I" .. include
end

-- ldflags
local ldflags = ""
if platform == "windows" then
	ldflags = "-lstdc++ -static"
else
	ldflags = "-lm"
end

-- man.
if compmode == "debug" then
	cflags = cflags .. " -Og -g -DDEBUG -D_DEBUG"
else
	cflags = cflags .. " -O3 -g -fno-omit-frame-pointer"
end

if sanitize ~= "" then
	cflags = cflags .. " -fsanitize=" .. sanitize
	ldflags = ldflags .. " -fsanitize=" .. sanitize
end

-- generate the build files frfrfr ong no cap
local f = io.open("build.ninja", "w")
assert(f)

f:write("# Autogenerated by configure.lua. You probably shouldn't edit this.\n")
f:write("cxx = " .. cxx .. "\n")
f:write("cflags = " .. cflags .. "\n")
f:write("ldflags = " .. ldflags .. "\n")
f:write("ar = ar\n")
f:write("arflags = rcs\n")

f:write("\nrule compile\n")
f:write("  command = $cxx $cflags -c $in -o $out\n")
f:write("  description = Compiling $in\n")

f:write("\nrule link\n")
f:write("  command = $cxx $in $ldflags -o $out\n")
f:write("  description = Linking $out\n")

f:write("\nrule archive\n")
f:write("  command = $ar $arflags $out $in\n")
f:write("  description = Archiving $out\n")

-- build crap :)
for _, src in ipairs(srcs) do
	f:write("build "..src:gsub("%.cpp", ".o")..": compile "..src.."\n")
end
for _, src in ipairs(test_srcs) do
	f:write("build "..src:gsub("%.cpp", ".o")..": compile "..src.."\n")
end

-- im archiving it
f:write("\nbuild libtrippin.a: archive ")
for _, src in ipairs(srcs) do
	f:write(src:gsub("%.cpp", ".o").." ")
end

-- link crap :)
f:write("\nbuild testingit: link ")
for _, src in ipairs(test_srcs) do
	f:write(src:gsub("%.cpp", ".o").." ")
end
f:write(" libtrippin.a")

f:write("\ndefault testingit\n")

f:close()

if compile_commands == "y" then
	os.execute("ninja -t compdb > compile_commands.json")
end
io.write("ok\n")
