name: Mirror to Codeberg
run-name: 'I am mirroring it...'
on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/hellory4n/libtrippin.git'
          GIT_USERNAME: hellory4n
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
