name: Mirror to Codeberg
run-name: 'I am mirroring it...'
on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'not-the-real-url.com/repo.git'
          GIT_USERNAME: username
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
